### ISSUE TITLE
test network with wrong crossed boxes

### ISSUE THREAD

**Issue by SidanPukich** [EvaluationHelper/EvaluationHelper-NN#21]

**Comment by SidanPukich** [comment]
Asked the question
https://ilias.studium.kit.edu/ilias.php?ref_id=1459773&cmdClass=ilobjforumgui&thr_pk=207859&cmd=viewThread&cmdNode=uk:lk&baseClass=ilrepositorygui

**Comment by NandoSun** [comment]
Ok  perfect so we dont need this
